Audit fixes
wolvesofwallstreet/wolves.finance pull request #110
Opened 2021-05-23 07:32 UTC by juztamau5

## Description

This PR addresses issues from the Bramah Systems audit.

One issue was fixed earlier in https://github.com/wolvesofwallstreet/wolves.finance/commit/0efbb0ac55dad8d5c6e08162c02ab68523594923. Most of the remaining issues are fixed in the commits here.

One item not addressed is:

```
## Unused variables should be removed
Controller.sol references an “amount” variable that should be removed.
```

@peak3d can you decide what do you about this one?

2021-05-23 07:58 UTC, peak3d commented on contracts/src/crowdsale/WOWSSftMinter.sol
> +  uint256 public nextCFolioItemNft = (1 << 64);
Have you verified that the 1 is treated as uint256 ? I had issues with that in the past without typecasting like uint256(1)<<64

2021-05-23 08:01 UTC, peak3d commented on contracts/src/utils/TokenIds.sol
> +    return (tokenId & HASH_MASK) < (1 << 64);
same, IMO the 1 has to be casted to an uint256(1)

2021-05-23 08:01 UTC, peak3d commented on contracts/src/utils/TokenIds.sol
> +    return (tokenId & HASH_MASK) < (1 << 32);
same

2021-05-23 08:03 UTC, peak3d reviewed
Thx for fixing, but we need to be sure that this is still working.
Remember the shift bug in ERC1155.

2021-05-25 10:27 UTC, peak3d commented
Regarding the unused amount: sure, let us remove it from impl.

```
--- a/contracts/src/investment/Controller.sol
+++ b/contracts/src/investment/Controller.sol
@@ -123,7 +123,7 @@ contract Controller is IController, Context, Ownable {
   /**
    * @dev See {IController-onDeposit}
    */
-  function onDeposit(uint256 amount)
+  function onDeposit(uint256/* amount*/)
     external
     view
     override
@@ -137,16 +137,13 @@ contract Controller is IController, Context, Ownable {
     require(farm.farmEndedAtBlock == 0, 'Farm closed');
     require(!farm.paused, 'Farm paused');

-    // Unused
-    amount;
-
     return 0;
   }

   /**
    * @dev See {IController-onDeposit}
    */
-  function onWithdraw(uint256 amount)
+  function onWithdraw(uint256/* amount*/)
     external
     view
     override
@@ -155,9 +152,6 @@ contract Controller is IController, Context, Ownable {
     // Validate state
     require(!farms[_msgSender()].paused, 'Farm paused');

-    // Unused
-    amount;
-
     return 0;
   }

```

2021-05-25 19:33 UTC, peak3d commented on contracts/src/utils/TokenIds.sol
>    uint256 public constant HASH_MASK = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;
(1 << 128) -1

2021-05-25 19:34 UTC, peak3d requested changes
I tested the (1 << XX) things and they work as expected.
can you finally please change the hashmask? Then it can go in

2021-05-26 06:09 UTC, juztamau5 commented
Thanks for testing. I added the hashmask. CI isn't green but I verified that it passes when based onto the last success so this is good to go.

2021-05-26 09:42 UTC, merged