Stablecoin investment tests
wolvesofwallstreet/wolves.finance pull request #117
Opened 2021-06-13 06:51 UTC by juztamau5

## Description

This PR adds Yearn and Curve as dependencies, implements stablecoin investing in CFIHSC, and adds test cases that correspond to, and expand upon, LP NFT tests.

I had to guess on some numbers, so they might need adjusting.

Note that USDT is not ERC-20 compliant, and has special handling in Curve. We might also need special handling in our code (for now the special handling is patched out in Curve). I marked such places with TODOs.

## How has this been tested?

Developed using CI, so runs should be green

2021-06-13 12:41 UTC, peak3d requested changes
Great work! There are some minor things to clearify, and I haven't looked that deep into the test system.
1.) we'll need the 2 new addresses also in generated_addresses.json in order to predefine them for the mainnet deployment (so same concept you implemented for OSProxyRegistry for example, or the Uniswap things).
2.) discussion point would be for both deposit and withdraw if we want to allow it for already existing YToken. maybe there are ppl. which have already something in curve, and want to earn wows without the expensive withdraw deposit procedure.
3.) We finally have to fixate the team invest things,  it is communicated to the crowd, so we have to implement it before we can pass it to audit.

2021-06-13 12:41 UTC, peak3d commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +      require(amounts.length == 4, 'Need DAI/USDC/USDT/TUSD');
require(amounts.length == 0 || amounts.length == 4, 'Need DAI/USDC/USDT/TUSD');

2021-06-13 12:41 UTC, peak3d commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +    for (uint256 i = 0; i < 4; ++i) {
I suspect that normal user only deposits one coin, from reading logs of curve, it cost quite some gas to call transfer for 0 value, IMO we should condition this here (and dont call all the stuff if no value given))

2021-06-13 12:41 UTC, peak3d commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +      IERC20(underlyingCoin).approve(address(curveYDeposit), tokenAmounts[i]);
Is this really required? I would assume that this is already done internally?
Edit: Nvm

2021-06-13 12:41 UTC, peak3d commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +    for (uint256 i = 0; i < 4; ++i) {
If we only allow one coin removal, then there is no loop required, correct? coinIndex should already point to the correct asset

2021-06-17 03:37 UTC, juztamau5 commented
Sorry for the delay, haven't been able to make it to a computer for four days. I'm starting to address the comments now. Here's some responses:

> 1.) we'll need the 2 new addresses also in generated_addresses.json in order to predefine them for the mainnet deployment (so same concept you implemented for OSProxyRegistry for example, or the Uniswap things).

I intended for this PR to include predefining the addresses, I'll look closer and see if that's actually the case.

> 2.) discussion point would be for both deposit and withdraw if we want to allow it for already existing YToken. maybe there are ppl. which have already something in curve, and want to earn wows without the expensive withdraw deposit procedure.

This is a good idea, but one problem is that we want to take a small percentage of the profit. If you invest some dai and get back more dai, then you can calculate a fee, because there was a profit in the deposited token. If you invest YToken and get back same amount of YToken, you can't take a fee, because YTokens increase in value, not in amount, so you'd be taking some of the principal.

I realized that we don't currently take a profit fee. I'm considering how this would be done, but I suggest we merge the PR and then follow up with this feature.

2021-06-17 04:47 UTC, juztamau5 commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +    for (uint256 i = 0; i < 4; ++i) {
Added a check. Surprisingly, in the test fixture, it costs less gas to deposit four even amounts than a single non-zero amount because less swapping is required.

2021-06-17 04:47 UTC, juztamau5 commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +      require(amounts.length == 4, 'Need DAI/USDC/USDT/TUSD');
Fixed, thanks

2021-06-17 05:13 UTC, juztamau5 commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +    for (uint256 i = 0; i < 4; ++i) {
Thanks, fixed

2021-06-17 06:09 UTC, juztamau5 commented
@peak3d pushed updates for your comments. Also added a commit to seed liquidity, as tests were unable to fully convert everything to DAI when the pool is empty. Also, I confirmed that unless the `IGNORE_ADDRESSES` is set, deployment will read addresses from `addresses.json`.

2021-06-17 07:39 UTC, peak3d commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +        IERC20(underlyingCoin).approve(address(curveYDeposit), newBalance);
Please make unlimited approvals once during contract initialization

2021-06-17 07:40 UTC, peak3d commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +      IERC20(underlyingCoin).approve(address(curveYDeposit), tokenAmount);
Please make unlimited approvals once during contract initialization

2021-06-17 07:40 UTC, peak3d commented on contracts/src/cfolio/CFolioItemHandlerSC.sol
> +    curveYToken.approve(address(curveYDeposit), amount);
Please make unlimited approvals once during contract initialization

2021-06-17 09:34 UTC, juztamau5 commented
TODO (listing so I can keep track):

* Approvals in constructor, proxy initialization
* Accept 5 amounts (DAI/USDC/USDT/TUSD/yCRV)
* getAmounts() for SFT minter
* min amount for withdrawal
* yCRV gauge (stretch goal)

2021-06-17 13:56 UTC, peak3d commented
> TODO (listing so I can keep track):
> 
> * Approvals in constructor, proxy initialization
> * Accept 5 amounts (DAI/USDC/USDT/TUSD/yCRV)
> * getAmounts() for SFT minter
> * min amount for withdrawal
> * yCRV gauge (stretch goal)

Pls. remove function calcWithdrawOneCoin(uint256, uint128)

2021-06-18 01:53 UTC, juztamau5 commented
@peak3d I was able to address all the comments I could track down. This should be ready for UI testing, unless you have more comments.

2021-06-18 01:58 UTC, juztamau5 commented
Actually still one TODO left: https://github.com/wolvesofwallstreet/wolves.finance/pull/117/files#diff-d753fb665839f96d7328712456b8f9c2484092835668b67e85fc9b3f874f05bfR143

2021-06-18 15:58 UTC, merged