Add test suite for Store component
wolvesofwallstreet/wolves.finance pull request #5
Opened 2021-01-31 23:33 UTC by juztamau5

## Description

This PR adds a test suite for the Store class, which connects to the wallets and performs transactions. I wrote this while testing the SFT purchase page, and decided to PR the store test suite separately while I work more on the purchase component.

The test suite renders the store component and digitally performs a "click" action on the form to initiate wallet connection. I swapped out web3modal for the truffle HDWallet when it's detected that we're running on CI infra vs. in the browser.

### Secrets

Requires the following GitHub Actions secret to be set:

  * INFURA_API_KEY
  * MNEMONIC

I use `dotenv-defaults` to manage environment variables, because it degrades gracefully both in the browser and in node. It pulls in values in the following order of preference:

* Environment variable set by CI runner
* Override specified in `.env` file (created by dev)
* Default specified in `.env.defaults` file (included in repo)

As a result, values can be provided on different levels with sensible defaults.

### Workarounds

#### Jest version

Jest 26 introduces a bug, so Jest 25 is required. See:

* https://github.com/facebook/jest/issues/7780#issuecomment-705566017

#### jsdom bug

A patch is required for `@ethersproject/providers` because it doesn't check for null values. Null values aren't allowed by the spec, so omitting the check is proper, but `jest-environemt-jsdom` (or `jsdom` itself) has timers that return null instead of an open handle.

See:

  * https://github.com/facebook/jest/issues/7933
  * https://github.com/bugsnag/bugsnag-js/issues/452

## How has this been tested?

Result of CI test:

```
|    $ react-scripts test --passWithNoTests
|    PASS src/__tests__/test-store.tsx (24.726 s)
|      ● Console
|
|        console.log
|          EventProvider launched on network:  rinkeby
|
|          at Store._launchEventProvider (src/stores/store.tsx:319:17)
```

We see the store component being rendered and submitted, and as a result the store connects to the network and logs its success: `EventProvider launched on network:  rinkeby`.

I had to insert large artificial pauses, because otherwise the test suite ends while web3 stuff is still going on in the background and it freezes the test runner. Adding the large pauses let background tasks settle before exiting, preventing the crashes. However, the web3 dependencies should be scrutinized to avoid this hack in the future.

2021-02-01 01:38 UTC, juztamau5 commented
Upon testing, it seems that the web3 stuff is hanging the test suite about 1/3 of the time. I'll try to fix this before landing the SFT pull request.

2021-02-05 01:25 UTC, juztamau5 commented
@peak3d I got CI to pass successfully now.

For security our GitHub Actions secrets aren't exposed to PRs from external repos, so I inserted my Infura API key for a default value. After merging I'll upload a team API key that'll be used for internal runs not triggered from external PRs.

2021-02-05 10:10 UTC, peak3d commented
Regarding the wait / web3js: Wouldn't it be possible to add the ganache node module, spawn it for the test and use the new private network option to test on local node?
We will have to do this also in the next time to be able to fast forward time to test the staking reward contracts.
Reference: uniswap liquidity-staking repo.

2021-02-05 10:32 UTC, peak3d requested changes

2021-02-05 10:32 UTC, peak3d commented on .env.defaults
> +PRIVATE_KEY=0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3
what is this private key?
From what I know env files should never be part of the public git repo.

2021-02-05 10:32 UTC, peak3d commented on .github/workflows/node.js.yml
>  ################################################################################
We should go with node ganache module and spawn our own eth node.
Then we can also remove the dotenv file in this git repo.

Having a private key and our private infura id in public git repo is IMO not the way to go.

2021-02-05 10:32 UTC, peak3d commented on src/stores/store.tsx
> +        );
I don't see the requirement adding truffle code here.
In ethers you create a "Wallet" which acts as the signer.

2021-02-05 10:32 UTC, peak3d commented on src/stores/store.tsx
> +        | ethers.providers.Web3Provider;
Web3Provider inherits from JsonRpcProvider, where do you need special access on web3Provider properties?

2021-02-05 10:35 UTC, peak3d commented
@juztamau5 sure we should add the possibility for HDWallets in the future, but this needs more work, for example listing all addresses. For the CI run I really want to suggest that we use local ganache, which is spawned on CI runtime.

It offers beside the fact that you don't have to implement HDWallet additionally great features like time fast-forwarding.

2021-02-24 20:35 UTC, juztamau5 commented
I'm going to close this. Given that @peak3d  is focusing on UI and I'm focusing on SOL, I'd like to not mingle them right now to give us both enhanced speed. It's not worth polluting UI with build system stuff

2021-02-24 20:35 UTC, closed without merging